### PR TITLE
Miscellaneous cleanup

### PR DESCRIPTION
**Pull request by absidue**
This pull request makes various changes with the goal of cleaning up the code and dependencies.

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
linter going crazy

**Comment by ChunkyProgrammer** [comment]
Yeah, the linter for this project wants semicolons at the end of lines

**Comment by ChunkyProgrammer** [comment]
Also npm run build seems to be failing

**Review by ChunkyProgrammer — APPROVED** [review]

**Comment by ChunkyProgrammer** [comment]
LGTM

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by PikachuEXE — APPROVED** [review]

**Pull request merged**
